### ISSUE TITLE
Input alignment file is not sorted.(metaDMG)

### ISSUE THREAD

**Issue by timeresistance1996** [metaDMG-dev/metaDMG-cpp#22]
Hallo，

    My .sam has been sorted with "samtools sort" before run "metaDMG-cpp getdamage -l 10 -p 5 --threads 8  sorted_output". But I got an error:

	-> metaDMG version: 0.4 (htslib: 1.19.1) build(Nov  1 2023 17:55:14)
	-> metaDMG-cpp getdamage -l 10 -p 5 --threads 8 output.sam 
	-> ./metaDMG-cpp refName: (null) min_length: 10 print_length: 5 run_mode: 0 out_prefix: meta nthreads: 8 ignore_errors: 0
	-> We require a proper header starting with @HD for metadamage
	-> We observed: '' will exit
Input alignment file is not sorted.(metaDMG)   

I install metaDMG on my Ubuntu with conda. How should I solve this?

**Comment by miwipe** [comment]
How does the header of the bam file look like?

Try doing samtools view -H filename.bam

There should be a @HD in the first line if not then that is the issue. And which programme did you use to create the bam file?

On 20 Mar 2024, at 15.19, timeresistance1996 ***@***.***> wrote:

﻿

Hallo，

My .sam has been sorted with "samtools sort" before run "metaDMG-cpp getdamage -l 10 -p 5 --threads 8  sorted_output". But I got an error:

-> metaDMG version: 0.4 (htslib: 1.19.1) build(Nov  1 2023 17:55:14)
-> metaDMG-cpp getdamage -l 10 -p 5 --threads 8 output.sam
-> ./metaDMG-cpp refName: (null) min_length: 10 print_length: 5 run_mode: 0 out_prefix: meta nthreads: 8 ignore_errors: 0
-> We require a proper header starting with @HD for metadamage
-> We observed: '' will exit


Input alignment file is not sorted.(metaDMG)

I install metaDMG on my Ubuntu with conda. How should I solve this?

**Comment by timeresistance1996** [comment]
Thanks for your reply!

    The code worked after I sorted with "samtools sort -n". But I still got a fault:
     metaDMG-cpp getdamage -l 10 -p 5 --threads 4 output.name.sort.bam
        -> metaDMG version: 0.4 (htslib: 1.19.1) build(Nov  1 2023 17:55:14)
        -> metaDMG-cpp getdamage -l 10 -p 5 --threads 4 output.name.sort.bam
        -> ./metaDMG-cpp refName: (null) min_length: 10 print_length: 5 run_mode: 0 out_prefix: meta nthreads: 4 ignore_errors: 0
skipping: SRR13615826.2 unmapped, this msg is printed: 2 times more
skipping: SRR13615826.2 unmapped, this msg is printed: 1 times more
skipping: SRR13615826.5 unmapped, this msg is printed: 0 times more
Segmentation fault (core dumped)

**Comment by timeresistance1996** [comment]
Thanks for your reply!

 The code worked after I sorted with "samtools sort -n". But I still got a fault:

metaDMG-cpp getdamage -l 10 -p 5 --threads 4 output.name.sort.bam
        -> metaDMG version: 0.4 (htslib: 1.19.1) build(Nov  1 2023 17:55:14)
        -> metaDMG-cpp getdamage -l 10 -p 5 --threads 4 output.name.sort.bam
        -> ./metaDMG-cpp refName: (null) min_length: 10 print_length: 5 run_mode: 0 out_prefix: meta nthreads: 4 ignore_errors: 0
skipping:  unmapped, this msg is printed: 2 times more
skipping:  unmapped, this msg is printed: 1 times more
skipping:  unmapped, this msg is printed: 0 times more
Segmentation fault (core dumped)

**Comment by ANGSD** [comment]
can you please try with the most recent version on github, there has been
quite a few changes over the last many months.

Den tors. 21. mar. 2024 kl. 07.21 skrev timeresistance1996 <
***@***.***>:

**Comment by ANGSD** [comment]
I think we should remove the program from conda until it has reached
production status, the conda version is very much out of sync with the main
github repos.

Den tors. 21. mar. 2024 kl. 10.37 skrev Mikkel Winther Pedersen <
***@***.***>:

**Comment by CCEK150** [comment]
Hello，I have the same question with writer. And I try with the most recent version on github. But how should I install libgsl-dev libeigen3-dev on CentOS7.3?

**Comment by ANGSD** [comment]
Make sure, you are using the most recent version. eigen should not be needed in the main parts that gets compiled by default.
If you have admin rights, then you can install gsl using the package system, otherwise you will have to do a local installation.

Best regards.

**Comment by timeresistance1996** [comment]
Yes, it's the problem that install with conda. I reinstalled metaDMG with git clone and compile successfully.

Thank you for you reply! @miwipe @ANGSD

**Comment by CCEK150** [comment]
I try to install metaDMG-cpp like #6: 
```
conda create -n metaDMG-cpp python=3.9 eigen htslib cxx-compiler gsl
conda activate metaDMG-cpp
git clone https://github.com/metaDMG-dev/metaDMG-cpp.git
cd metaDMG-cpp
make HTSSRC=../htslib/`
```
But I get the error: 
```
gcc -g -Wall -O2 -fvisibility=hidden  -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -fvisibility=hidden  -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -fvisibility=hidden  -I.  -c -o bcf_sr_sort.o bcf_sr_sort.c
gcc -g -Wall -O2 -fvisibility=hidden  -I.  -c -o bgzf.o bgzf.c
bgzf.c:38:10: fatal error: zlib.h: No such file or directory
   38 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make[1]: *** [bgzf.o] Error 1
make[1]: Leaving directory `home/user/metaDMG-cpp/htslib'
make: *** [.activate_module] Error 2
```
could you please help me to understand how to solve it?

**Comment by ANGSD** [comment]
i would just do it regularly.

git clone --recursive https://github.com/samtools/htslib
cd htslib
make
cd ..
git clone https://github.com/metaDMG-dev/metaDMG-cpp
cd metaDMG-cpp
make HTSSRCC=../htslib

**Comment by ANGSD** [comment]
Hi I didnt read the email properly, it looks like you are missing the zlib.h from your operating system. You will need to install that.

From a quick google search, you should be able to install it like:

yum install zlib-devel

**Comment by CCEK150** [comment]
Thanks for your answer, but now our system has some problems, we can't use the yum library..., look forward to the version update on conda
