### ISSUE TITLE
Error in make command

### ISSUE THREAD

**Issue by MinLuke** [metaDMG-dev/metaDMG-cpp#6]
Goodmorning,
After installing htslib as indicated I downloaded the metaDM.cpp.git , I entered in the folder and execute make HTSSRC = ../htslib/ 
But I get the following message and I do not understand why I am getting this error, could you please help me to understand how to solve it?

`Crypto library is available to link; adding -lcrypto to LIBS
HTSSRC not defined, assuming systemwide installation -lhts
g++ -c  -O3 -std=c++11   ngsLCA.cpp
ngsLCA.cpp:4:56: fatal error: htslib/hts.h: File o directory not exist
 #include <htslib/hts.h>  // for htsFormat, seq_nt16_str
                                                        ^
compilation terminated.
make: *** [ngsLCA.o] Error 1`

**Comment by ANGSD** [comment]
Could you supply me with the full output of the compilation process;
make clean;make HTSSRC=../htslib/

Den ons. 25. jan. 2023 kl. 10.34 skrev MinLuke ***@***.***>:

**Comment by ANGSD** [comment]
ok, complains that eigen hasnt been installed.

If you are on ubuntu the dependencies can be installed with.

sudo apt install libgsl-dev libeigen3-dev


Den ons. 25. jan. 2023 kl. 11.31 skrev MinLuke ***@***.***>:

**Comment by miwipe** [comment]
Alternatively you can install the dependencies using conda/mamba:

# installation of metaDMG-cpp, by making environment with dependencies
mamba create -n metaDMG-cpp python=3.9 eigen htslib cxx-compiler gsl

# next activate the conda environment
conda activate metaDMG-cpp

#install metaDMG-cpp
git clone https://github.com/metaDMG-dev/metaDMG-cpp.git
cd metaDMG-cpp
make

# Now finally install metaDMG-core
pip install metaDMG[all]

**Comment by MinLuke** [comment]
thanks, is it possible to perform the installation of eigen if im not an administrator?

**Comment by miwipe** [comment]
The conda installation should work with any type of rights.

Mikkel Winther Pedersen
Assistant Professor
Head Web coordinator at Globe Institute

University of Copenhagen
Globe Institute
Section for GeoGenetics
Øster Voldgade 5-7
1350 Copenhagen K
DENMARK

TEL +45 29 27 53 42
***@***.******@***.***>
https://globe.ku.dk/research/geogenetics/paleo-environmental-genomics-group/

***@***.***


From: MinLuke ***@***.***>
Reply to: metaDMG-dev/metaDMG-cpp ***@***.***>
Date: Wednesday, 25 January 2023 at 14.00
To: metaDMG-dev/metaDMG-cpp ***@***.***>
Cc: Mikkel Winther Pedersen ***@***.***>, Comment ***@***.***>
Subject: Re: [metaDMG-dev/metaDMG-cpp] Error in make command (Issue #6)


thanks, is it possible to perform the installation of eigen if im not an administrator?

**Comment by miwipe** [comment]
Try to search the channel conda-forge, e.g.

mamba create -n metaDMG-cpp -c conda-forge python=3.9 eigen htslib cxx-compiler gsl

https://anaconda.org/conda-forge/cxx-compiler

From: MinLuke ***@***.***>
Reply to: metaDMG-dev/metaDMG-cpp ***@***.***>
Date: Wednesday, 25 January 2023 at 14.04
To: metaDMG-dev/metaDMG-cpp ***@***.***>
Cc: Mikkel Winther Pedersen ***@***.***>, Comment ***@***.***>
Subject: Re: [metaDMG-dev/metaDMG-cpp] Error in make command (Issue #6)


Using mamba command line I get

Encountered problems while solving:

  - nothing provides requested cxx-compiler

**Comment by MinLuke** [comment]
Ok now better but I am getting another error

```
Crypto library is available to link; adding -lcrypto to LIBS
HTSSRC not defined, assuming systemwide installation -lhts
echo '#define METADAMAGE_VERSION "0.2-46-gedaf069"' > version.h
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -c  -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  ngsLCA.cpp
ngsLCA.cpp: In function 'char2int setlevels(int, char*, int&)':
ngsLCA.cpp:64:42: warning: ISO C++ forbids converting a string constant to 'std::map<char*, int, cmp_str>::key_type' {aka 'char*'} [-Wwrite-strings]
   64 |         char2int::iterator it = c2i.find("species");
      |                                          ^~~~~~~~~
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -MM -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  ngsLCA.cpp >ngsLCA.d
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -c  -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  ngsLCA_cli.cpp
ngsLCA_cli.cpp: In function 'void pars_free(pars*)':
ngsLCA_cli.cpp:55:9: error: 'sam_hdr_destroy' was not declared in this scope; did you mean 'bam_hdr_destroy'?
   55 |         sam_hdr_destroy(p->header);
      |         ^~~~~~~~~~~~~~~
      |         bam_hdr_destroy
make: *** [ngsLCA_cli.o] Errore 1

```

**Comment by miwipe** [comment]
Which system are you trying to install it on.?

It seems your htslib didn’t install probably. Also when you are sending these errors it would be helpful to see the commands too.


From: MinLuke ***@***.***>
Reply to: metaDMG-dev/metaDMG-cpp ***@***.***>
Date: Wednesday, 25 January 2023 at 14.34
To: metaDMG-dev/metaDMG-cpp ***@***.***>
Cc: Mikkel Winther Pedersen ***@***.***>, Comment ***@***.***>
Subject: Re: [metaDMG-dev/metaDMG-cpp] Error in make command (Issue #6)


Ok now better but I am getting another error

Crypto library is available to link; adding -lcrypto to LIBS

HTSSRC not defined, assuming systemwide installation -lhts

echo '#define METADAMAGE_VERSION "0.2-46-gedaf069"' > version.h

/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -c  -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  ngsLCA.cpp

ngsLCA.cpp: In function 'char2int setlevels(int, char*, int&)':

ngsLCA.cpp:64:42: warning: ISO C++ forbids converting a string constant to 'std::map<char*, int, cmp_str>::key_type' {aka 'char*'} [-Wwrite-strings]

   64 |         char2int::iterator it = c2i.find("species");

      |                                          ^~~~~~~~~

/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -MM -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  ngsLCA.cpp >ngsLCA.d

/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -c  -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  ngsLCA_cli.cpp

ngsLCA_cli.cpp: In function 'void pars_free(pars*)':

ngsLCA_cli.cpp:55:9: error: 'sam_hdr_destroy' was not declared in this scope; did you mean 'bam_hdr_destroy'?

   55 |         sam_hdr_destroy(p->header);

      |         ^~~~~~~~~~~~~~~

      |         bam_hdr_destroy

make: *** [ngsLCA_cli.o] Errore 1

**Comment by MinLuke** [comment]
Yes, sorry.
Ok, I do not have mamba on this server (of which i am not sudoer) , but I have conda so I used:
`conda create -n metaDMG-cpp -c conda-forge python=3.9 eigen htslib cxx-compiler gsl`

Linux p04-64gb 3.10.0-1160.81.1.el7.x86_64

**Comment by miwipe** [comment]
all ok., but the above message must be from trying to install metaDMG-cpp afterwards? No the above command right?

**Comment by miwipe** [comment]
yes, will you htslib is not installed correctly I think or metaDMG cannot find it?  

try again with the make HTSSRC=../htslib/ 

and make sure the path points to the htslib folder.

**Comment by MinLuke** [comment]
Thanks now better but I get another error
```
make HTSSRC=../metaDMG-core/htslib/

Crypto library is available to link; adding -lcrypto to LIBS
HTSSRC defined
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -c  -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  -I/home/minluk/script/metaDMG-core/htslib ngsLCA_cli.cpp
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -MM -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  -I/home/minluk/script/metaDMG-core/htslib ngsLCA_cli.cpp >ngsLCA_cli.d
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -c  -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  -I/home/minluk/script/metaDMG-core/htslib main_pmd.cpp
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -MM -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  -I/home/minluk/script/metaDMG-core/htslib main_pmd.cpp >main_pmd.d
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -c  -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  -I/home/minluk/script/metaDMG-core/htslib profile.cpp
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -MM -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  -I/home/minluk/script/metaDMG-core/htslib profile.cpp >profile.d
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -c  -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  -I/home/minluk/script/metaDMG-core/htslib metaDMG.cpp
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -MM -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  -I/home/minluk/script/metaDMG-core/htslib metaDMG.cpp >metaDMG.d
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -c  -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  -I/home/minluk/script/metaDMG-core/htslib shared.cpp
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -MM -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  -I/home/minluk/script/metaDMG-core/htslib shared.cpp >shared.d
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -c  -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  -I/home/minluk/script/metaDMG-core/htslib regression.cpp
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -MM -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/miniconda3/envs/metaDMG-cpp/include -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib  -I/home/minluk/script/metaDMG-core/htslib regression.cpp >regression.d
/opt/miniconda3/envs/metaDMG-cpp/bin/x86_64-conda-linux-gnu-c++ -O3 -std=c++11  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/opt/miniconda3/envs/metaDMG-cpp/lib -Wl,-rpath-link,/opt/miniconda3/envs/metaDMG-cpp/lib -L/opt/miniconda3/envs/metaDMG-cpp/lib -o metaDMG-cpp *.o /home/minluk/script/metaDMG-core/htslib/libhts.a -lz -llzma -lbz2 -lpthread -lcurl -lgsl -lgslcblas -lcrypto
/opt/miniconda3/envs/metaDMG-cpp/bin/../lib/gcc/x86_64-conda-linux-gnu/11.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/minluk/script/metaDMG-core/htslib/libhts.a(kstring.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/opt/miniconda3/envs/metaDMG-cpp/bin/../lib/gcc/x86_64-conda-linux-gnu/11.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make: *** [metaDMG-cpp] Error 1
```

**Comment by genomewalker** [comment]
```
ngsLCA_cli.cpp:55:9: error: 'sam_hdr_destroy' was not declared in this scope; did you mean 'bam_hdr_destroy'?

   55 |         sam_hdr_destroy(p->header);

      |         ^~~~~~~~~~~~~~~

      |         bam_hdr_destroy

make: *** [ngsLCA_cli.o] Errore 1
```
@MinLuke you need to set up the correct order of the conda channels. This error message is related that you are installing an old version. Reinstall _htslib_ but using the one in the _bioconda_ channel. Then it should work.

**Comment by miwipe** [comment]
these are my channels in their priority
└─ $ ▶ conda config --show channels
channels:
  - conda-forge
  - bioconda
  - defaults

**Comment by MinLuke** [comment]
` conda config --show channels
channels:
  - defaults
`

**Comment by miwipe** [comment]
then add first
conda config --add channels bioconda 
then
conda config --add channels conda-forge 

And rerun the installation using conda perhaps in a new environment name.

**Comment by miwipe** [comment]
oh and check your channel priority first that it matches the one above.

**Comment by MinLuke** [comment]
Ok once they are in the right order what do I have to do? 
conda install htslib?
and once made it , can I run the make in metaDMG-cpp folder?

**Comment by miwipe** [comment]
I suggest you delete the environment you have and redo the creation of the environment etc. 


### installation of metaDMG-mdmg_cpp
conda create -n metaDMG-cpp2 python=3.9 eigen htslib cxx-compiler gsl

### install all dependencies etc. next activate the conda environment
conda activate metaDMG-cpp2

###install metaDMG-cpp
git clone https://github.com/metaDMG-dev/metaDMG-cpp.git
cd metaDMG-cpp
make

### Now finally install metaDMG-core
pip install metaDMG[all]

**Comment by miwipe** [comment]
Now this should work.

**Comment by MinLuke** [comment]
it works!! thank you all for this precious support
